directory: git+https://github.com/microsoft/amplifier/directory.git@v0.2.0
paths:
  data_dir: .data
  content_dirs:
  - .data/content
models:
  fast: claude-3-5-haiku-20241022
  default: claude-sonnet-4-20250514
  thinking: claude-opus-4-1-20250805
  knowledge_mining: claude-3-5-haiku-20241022
  knowledge_extraction: claude-sonnet-4-20250514
content_processing:
  max_chars: 50000
  classification_chars: 1500
knowledge_mining:
  storage_dir: .data/knowledge_mining
  default_doc_type: general
  max_chars: 50000
  classification_chars: 1500
  model: claude-3-5-haiku-20241022
  extraction_model: claude-sonnet-4-20250514
memory_system:
  enabled: false
  model: claude-3-5-haiku-20241022
  timeout: 120
  max_messages: 20
  max_content_length: 500
  max_memories: 10
  storage_dir: .data/memories
smoke_test:
  model_category: fast
  skip_on_ai_unavailable: true
  ai_timeout: 30
  max_output_chars: 5000
  test_data_dir: .smoke_test_data
optional:
  debug: false
  anthropic_api_key: null
