[project]
name = "amplifier-mod-tool-task"
version = "0.1.0"
description = "Task delegation tool for Amplifier sub-agents"
dependencies = [
    "amplifier-core>=0.1.0"
]

[project.entry-points."amplifier.modules"]
tool-task = "amplifier_mod_tool_task:mount"