# Amplifier Full Features Test Configuration
# Tests all newly implemented features for feature parity with Claude Code

[provider]
name = "anthropic"
model = "claude-3-5-sonnet-20241022"

[modules]
orchestrator = "loop-basic"
context = "context-simple"  # Use simple context for testing
tools = [
    "filesystem",    # Read, Write, Edit with diff
    "bash",          # Command execution
    "web",           # Web fetch and search (now with real DuckDuckGo)
    "search",        # NEW: Grep, Glob, Find
    "task"           # NEW: Sub-agent delegation
]
agents = [
    "architect"      # Specialized agent (ready for task delegation)
]

# Hook modules configuration - at top level
hooks = [
    {module = "hooks-logging", config = {level = "INFO", output = "console", file = "amplifier.log"}}
]

[context]
memory_files = [
    "./CLAUDE.md",
    "./AGENTS.md"
]
max_tokens = 200000
compact_threshold = 0.92

[session]
max_tokens = 100000
auto_compact = true

# Tool-specific configurations
[tools.bash]
require_approval = true

[tools.web]
timeout = 10
max_size = 1048576  # 1MB

[tools.search]
max_results = 100

[tools.task]
max_depth = 3
inherit_tools = true